### PR TITLE
Update objectives.properties

### PR DESCRIPTION
**Pull request by cloud7707**
New National Objectives

### CODE REVIEW

**Comment by panther2** [comment]
@cloud7707 
You remove data for both the 1941 and 1942 scenario but add only data for the 1941 scenario. 
Do you want to change the content of the NOs of the core game? In that case please create a new variant of the game with a different name of the game. This repository is for the core game, so you should not change or mess up anything game specific here.

**Comment by cloud7707** [comment]
Hallo panther2,

sorry for the confusion, I hope I didnt alter the file or anything. I tried to create a modification of the world war II v3 1941 scenario with new objectives. I now used the files from my triplea game and altered the xml files to edit the National Objectives. It is working fine and I would like to upload these files so that they are available for download via triplea. 

Apparently, Triplelk Jason Clark, Zero Pilot Mike McCaughey, ComradeKev and Seidelin made this version so I'd like to ask for their permission first. Since you answered my request, you do not happen to be one of them with a different username now?

You might not be responsible for this request, but of course I appreciate all help I can get.

Regards,

Cloud7707

**Comment by cloud7707** [comment]
(I had to adjust multiple NOs though so the change I did here on Github is no longer up to date)

**Comment by panther2** [comment]
> (I had to adjust multiple NOs though so the change I did here on Github is no longer up to date)

I recommend that you close this Pull Request, then.

As long as you don't change files in this repository you are free to change whatever you want. Just do it in a separate repository. What means adding a "new" (modified) game rather than modifying an existing one.

Thank you 🙂

**Comment by cloud7707** [comment]
Sure thing! It should be closed now. :)

**Pull request closed without merging**
